### PR TITLE
Remove incubator

### PR DESCRIPTION
**Pull request by guoyuepeng**

### CODE REVIEW

**Comment by toyboxman** [comment]
LGTM

**Comment by bhlx3lyx7** [comment]
Seems like we need to remove DISCLAIMER file like: https://github.com/apache/servicecomb-java-chassis/commit/0cb194b384c6edd99a26c11054dd6723307c9b84

**Comment by ahutsunshine** [comment]
Why does griffin homepage link still use https://griffin.incubator.apache.org instead of  https://griffin.apache.org/? Others look good to me.

**Comment by bhlx3lyx7** [comment]
@ahutsunshine the repo of homepage is another one for griffin-site

**Comment by guoyuepeng** [comment]
> Why does griffin homepage link still use https://griffin.incubator.apache.org instead of https://griffin.apache.org/? Others look good to me.

Where do you find the link of https://griffin.incubator.apache.org, our home page is https://griffin.apache.org

**Comment by ahutsunshine** [comment]
@guoyuepeng I find two places. One is References - Home Page in README.md and the other is `<a href="https://griffin.incubator.apache.org/" target="_blank">` in ui/angular/src/app/app.component.html.

**Pull request closed without merging**
