### PR TITLE
[Griffin 294] bugfix for completness enumeration wrong sql

### PR DESCRIPTION
**Pull request by LittleZhao**
if there is only 'hive_none' in enumeration values list, it will generate wrong sql. Update code to fix this bug

### CODE REVIEW

**Comment by LittleZhao** [comment]
here is the bug detail

if the error.confs looks like
`"error.confs": [
          {
            "values": [
              "hive_none"
            ], 
            "type": "enumeration", 
            "column.name": "abc"
          }
        ]`

the where clause is `(((`abc` IN ())) OR (`abc` IS NULL))`, it is a wrong where clause. It should be `(`abc` IS NULL)`

The pr fixes this bug.

**Comment by guoyuepeng** [comment]
hi, could you provide the related test case?

**Comment by LittleZhao** [comment]
> hi, could you provide the related test case?

I do not find the UT entrance for `CompletenessExpr2DQSteps.getDQSteps`, could you please tell me how to add ut for this part?

**Comment by wankunde** [comment]
LGTM

**Comment by guoyuepeng** [comment]
ok, we will create a test case for it soon.

**Pull request closed without merging**
