### PR TITLE
[GRIFFIN-345] Support cross-version compilation for Scala and Spark dependencies

### PR DESCRIPTION
**Pull request by chitralverma**
**What changes were proposed in this pull request?**

_This PR affects only the measure module._

In newer environments specially clouds, Griffin measure module may face compatibility issues due the old Scala and Spark versions. To remedy this following topics are covered in this ticket,

- Cross-compilation across scala major versions (2.11, 2.12)
- Update Spark Version (2.4+)
- Create maven profiles to build different scala and spark versions
- Changes to build strategy

This process is also done is apache spark to build for different versions of Scala and Hadoop.

**Does this PR introduce any user-facing change?**
No

**How was this patch tested?**
Via maven build process.

### CODE REVIEW

**Comment by chitralverma** [comment]
@wankunde @guoyuepeng  please review this

**Comment by wankunde** [comment]
@chitralverma Hi, chitralverma , I think it's very useful to support cross-version compilation for Scala and Spark dependencies. Since spark 3 has been released for some time, can we support it at the same time?

**Comment by chitralverma** [comment]
@wankunde spark 3 has some interface changes but let me check

**Comment by chitralverma** [comment]
@wankunde @guoyuepeng Just added support for cross version build against Spark 3.0.2 as well ! 🎉

**Review by chitralverma — COMMENTED** [review]
Self review done

**Comment by wankunde** [comment]
LGTM

**Comment by guoyuepeng** [comment]
LGTM!
Thanks guys.
@chitralverma @wankunde

**Comment by chitralverma** [comment]
Great, I'll merge this then when I'm back working next.

**Comment by chitralverma** [comment]
merged!

**Pull request closed without merging**
