### PR TITLE
[GRIFFIN-271] Before 0.6.0 milestone release, We need to check and tr…

### PR DESCRIPTION
**Pull request by toyboxman**
…im current codes against apache griffin dev guide

trim current java code by dev guide document

### CODE REVIEW

**Comment by guoyuepeng** [comment]
@toyboxman 
Could you fix the build error?

Thanks
William

**Comment by ahutsunshine** [comment]
@toyboxman 
You comment out `private RestTemplate restTemplate = new RestTemplate();` in SparkSubmitJob, so please fix testExecuteWithNoPredicateSuccess test in SparkSubmitJobTest to make all tests passed. Thanks.

**Fix:** 
just comment out `Whitebox.setInternalState(sparkSubmitJob, "restTemplate", restTemplate);`.

**Comment by toyboxman** [comment]
@ahutsunshine @guoyuepeng 

thanks for reminding.

I have found testcase and fix it.

**Comment by guoyuepeng** [comment]
LGTM

**Pull request closed without merging**
