### PR TITLE
Griffin 2.0.0 arch

### PR DESCRIPTION
**Pull request by guoyuepeng**
Our new architecture consists of two primary layers: the Data Quality Layer and the Integration Layer.

### Data Quality Layer

This layer abstracts the core concepts of the data quality lifecycle, focusing on:

- **Defining Specific Data Quality**:
  - **Metrics**: Establishing specific data quality metrics.
  - **Anomaly Detection**: Implementing methods for detecting anomalies.
  - **Actions**: Defining actions to be taken based on the data quality assessments.

- **Measuring Data Quality**:
  - Utilizing various connectors such as SQL, HTTP, and CMD to measure data quality across different systems.

- **Unifying Data Quality Results**:
  - Creating a standardized view of data quality results across different dimensions to ensure a consistent understanding.

- **Flexible Data Quality Jobs**:
  - Designing data quality jobs within a generic, topological Directed Acyclic Graph (DAG) framework to facilitate easy plug-and-play functionality.

### Integration Layer

This layer provides a robust framework to enable users to integrate Griffin data quality pipelines seamlessly with their business processes. It includes:

- **Scheduler Integration**:
  - Ensuring seamless integration with typical schedulers for efficient pipeline execution.

- **Apache DolphinScheduler Integration**:
  - Facilitating effortless integration within the Java ecosystem to leverage Apache DolphinScheduler.

- **Apache Airflow Integration**:
  - Enabling smooth integration within the AI ecosystem using Apache Airflow.

This architecture aims to provide a comprehensive and flexible approach to managing data quality and integrating it into various business workflows.

### CODE REVIEW

**Comment by guoyuepeng** [comment]
we decide to update apache griffin arch, please comments and contribute.

**Comment by chitralverma** [comment]
@guoyuepeng adding data integration to griffin with a ui seems to be a good idea.
are we planning UI changes as well?

my suggestion is to,
- Use logstash/ Apache Spark/ DBT/ Polars / Apache Datafusion backends for data integration
- Griffin data quality rules for DQ
- Scheduling by Apache Airflow
- and cataloguing/ lineage collection by [Datahub](https://github.com/datahub-project/datahub)

all of this via one UI.

If this makes sense, then I can create an architecture doc for this

**Comment by guoyuepeng** [comment]
> @guoyuepeng adding data integration to Griffin with a UI seems like a good idea. are we planning UI changes as well?
> 
> my suggestion is to,
> 
> * Use logstash/ Apache Spark/ DBT/ Polars / Apache Datafusion backends for data integration
> * Griffin data quality rules for DQ
>   
>   * This can be pull or push based
> * Scheduling by Apache Airflow
> * and cataloguing/ lineage collection by [Datahub](https://github.com/datahub-project/datahub)
> 
> all of this via one UI.
> 
> If this makes sense, then I can create an architecture doc for this

@chitralverma 
Since we will change a lot based on this proposal, UI will definitely need upgrade as well.

When I say integration, I don't mean data integration, I mean append data quality checking pipelines behind usual ETL pipelines.
```
existing enterprise data ETL pipelines   -> data quality checking pipelines(contributed by apache griffin)

ETLJob  ---> ETLJob will becomes

ETLJob  ---> ETLJob
    |                  ^
    |                  | (optional) 
    ---> DQJob  

```
About scheduling, I think each data org already has its own scheduler, scheduling their daily data jobs.
So it is really hard to ask them to setup and support a new scheduler, I want to leverage existing scheduler, we just need to generate job plan and somehow ingest our data quality jobs into existing job DAG. 
Of course, we can provide a default scheduler, but this scheduler is replaceable.

for data lineage, which is very important for troubleshooting, especially when data quality issue has been identified and we need to fix data qualtiy issue, we need go through lineage to fix the origin code, no matter it is SQL or python .

**Comment by chitralverma** [comment]
okay, got it.

**Comment by guoyuepeng** [comment]
@chitralverma 

Griffin focuses on standardizing data quality, leveraging the Apache community for data ingestion. Think of Griffin as the JUnit for data quality, but with the flexibility to integrate into various build workflows such as Maven, Gradle, and more.

Additionally, we need to prepare and move forward to integrate Apache Griffin into mainstream scheduling systems such as DolphinScheduler and Airflow.

**Comment by toyboxman** [comment]
@guoyuepeng ,

As the change we are dicussing is a great one, could you give more clarifications here?

I mean you can give a high level diagram to make clear of what to do/not to do in the new architecture. I think everyone in Griffin community needs to get to the same page.

**Comment by john-liu** [comment]
some idea for the integration part:
* It is not only to integrate the DQ checking/validation action into the orginal data pipeline, but also to have an option to have the validation as mandatory. 
* besides the mutli-dimentional dq result, there should be more option to define what is a dq failure so that the failure will cause the original data pipeline failure
* dq failure could be defined as per dimentional, also could be defined based on a Reducer Function

**Comment by john-liu** [comment]
would it be better to have this as v2?

**Comment by guoyuepeng** [comment]
> some idea for the integration part:
> 
> * It is not only to integrate the DQ checking/validation action into the orginal data pipeline, but also to have an option to have the validation as mandatory.
> * besides the mutli-dimentional dq result, there should be more option to define what is a dq failure so that the failure will cause the original data pipeline failure
> * dq failure could be defined as per dimentional, also could be defined based on a Reducer Function, for example, in the simplest way, a default weighted average function would be good enough to start.

data quality standard in the first layer should cover all these details, 
reduce(dq_result(dimension_1), dq_result(dimension_2),...)  -> DQ_Result

**Comment by guoyuepeng** [comment]
> @guoyuepeng ,
> 
> As the change we are dicussing is a great one, could you give more clarifications here?
> 
> I mean you can give a high level diagram to make clear of what to do/not to do in the new architecture. I think everyone in Griffin community needs to get to the same page.

yes, I will initialize this part.

**Comment by guoyuepeng** [comment]
> would it be better to have this as v2?

not a problem for me.

**Comment by whhe** [comment]
Seems the proposed architecture will be very scalable. I think we can first determine the main interfaces and make the whole process run smoothly based on the existing features (MySQL datasource, SQL rule and accuracy dimension with quartz scheduler). Other extensions like more data sources and UDF support can be determined later. 

I suggest to draft a detailed proposal on Google Docs or some other platforms, just like [FLIP](https://cwiki.apache.org/confluence/display/FLINK/FLIP+Template). Once it's finalized, we can develop the modules separately.

**Comment by photogamerun** [comment]
> Seems the proposed architecture will be very scalable. I think we can first determine the main interfaces and make the whole process run smoothly based on the existing features (MySQL datasource, SQL rule and accuracy dimension with quartz scheduler). Other extensions like more data sources and UDF support can be determined later.
> 
> I suggest to draft a detailed proposal on Google Docs or some other platforms, just like [FLIP](https://cwiki.apache.org/confluence/display/FLINK/FLIP+Template). Once it's finalized, we can develop the modules separately.

yes, that's good idea, we will do it.

**Comment by chitralverma** [comment]
> Seems the proposed architecture will be very scalable. I think we can first determine the main interfaces and make the whole process run smoothly based on the existing features (MySQL datasource, SQL rule and accuracy dimension with quartz scheduler). Other extensions like more data sources and UDF support can be determined later.
> 
> I suggest to draft a detailed proposal on Google Docs or some other platforms, just like [FLIP](https://cwiki.apache.org/confluence/display/FLINK/FLIP+Template). Once it's finalized, we can develop the modules separately.

https://github.com/apache/griffin/blob/master/griffin-doc/dev/griffin-pip.md
I wrote something for this a while back.

**Comment by guoyuepeng** [comment]
init DQDiagrams doc

**Comment by guoyuepeng** [comment]
> > Seems the proposed architecture will be very scalable. I think we can first determine the main interfaces and make the whole process run smoothly based on the existing features (MySQL datasource, SQL rule and accuracy dimension with quartz scheduler). Other extensions like more data sources and UDF support can be determined later.
> > I suggest to draft a detailed proposal on Google Docs or some other platforms, just like [FLIP](https://cwiki.apache.org/confluence/display/FLINK/FLIP+Template). Once it's finalized, we can develop the modules separately.
> 
> yes, that's good idea, we will do it.

After we finalize the design, we can work a plan to implement it.

**Pull request merged**
