### PR TITLE
GRIFFIN-279 Upgrade Spring boot to 2.1.7.RELEASE

### PR DESCRIPTION
**Pull request by joohnnie**
As spring boot 1.x is end of life Aug 1st 2019, it would be great to migrate to 2.1.x.

Below is the announcement

https://spring.io/blog/2018/07/30/spring-boot-1-x-eol-aug-1st-2019

Migrate Guide is 

https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0-Migration-Guide

### CODE REVIEW

**Comment by joohnnie** [comment]
the failure is caused by JIRA https://issues.apache.org/jira/browse/GRIFFIN-280

**Comment by guoyuepeng** [comment]
thanks, joohnnie.
could you fix those conflicts?

Thanks, William

**Comment by joohnnie** [comment]
William,
Will create a new PR before fix the issue of build

**Comment by guoyuepeng** [comment]
sure

**Comment by ahutsunshine** [comment]
Btw, I build and run 2.1.7.RELEASE, but there are some errors in my project.
1.BaseJpaRepository.class
`Error:(26, 68) java: type argument ID is not within bounds of type-variable ID`
`Error:(28, 20) java: cannot find symbol
  symbol:   method findById(ID)
  location: interface org.apache.griffin.core.job.repo.BaseJpaRepository<T,ID>`
2.BatchJobOperatorImpl.class
`Error:(314, 21) java: cannot find symbol
  symbol:   method saveAll(java.util.List<org.apache.griffin.core.job.entity.JobInstanceBean>)
  location: variable instanceRepo of type org.apache.griffin.core.job.repo.JobInstanceRepo`
Please take a look, thanks.

**Comment by joohnnie** [comment]
@ahutsunshine would you make sure you are using 2.1.7.RELEASE?
as the two methods you mentioned are introduced in spring boot 2.x, not exist in 1.5.x

Thanks

**Comment by ahutsunshine** [comment]
@joohnnie 
yes, I use 2.1.7.RELEASE. The whole project is pulled from github by `git fetch origin pull/523/head:upgrade` and built. Also, I see service pom.xml is 2.1.7.RELEASE and all are imported and no errors in it.
```
 <properties>
        <hadoop.version>2.7.1</hadoop.version>
        <hive.version>2.2.0</hive.version>
        <scala.version>2.10</scala.version>
        <spring.boot.version>2.1.7.RELEASE</spring.boot.version>
        <spring.security.kerberos.version>1.0.1.RELEASE</spring.security.kerberos.version>
        <confluent.version>3.2.0</confluent.version>
        <quartz.version>2.2.2</quartz.version>
        <start-class>org.apache.griffin.core.GriffinWebApplication</start-class>
        <powermock.version>2.0.2</powermock.version>
        <spring-boot-maven-plugin.version>2.1.7.RELEASE</spring-boot-maven-plugin.version>
        <derby.version>10.14.1.0</derby.version>
        <eclipselink.version>2.6.0</eclipselink.version>
        <mysql.java.version>5.1.47</mysql.java.version>
        <postgresql.version>9.4.1212.jre7</postgresql.version>
        <livy.core.version>0.3.0</livy.core.version>
        <elasticsearch-rest-client.version>6.2.4</elasticsearch-rest-client.version>
        <jackson-databind.version>2.9.9.3</jackson-databind.version>
    </properties>
```

**Comment by joohnnie** [comment]
@ahutsunshine thanks for the confirmation.

BaseJpaRepository is extended from JpaRepository and JpaRepository is the subclass of CrudRepository


https://docs.spring.io/spring-data/commons/docs/current/api/org/springframework/data/repository/CrudRepository.html?is-external=true#findById-ID-


Would you navigate to CrudRepository class from your IDE and check the jar it belongs to?

**Pull request closed without merging**
