### PR TITLE
update hibernate_mysql_pom.xml

### PR DESCRIPTION
**Pull request by guoyuepeng**

### CODE REVIEW

**Comment by guoyuepeng** [comment]
@ahutsunshine 
could you verify and provide relate application-mysql.properties ?

**Comment by guoyuepeng** [comment]
> Should we rather retire separate pom file and use maven profiles for that?

yeap, here a litter bit tricky is that hibernate and mysql's license, we cannot explicitly or implicitly say our preference for hibernate and mysql in apache.

**Comment by ahutsunshine** [comment]
> @ahutsunshine
> could you verify and provide relate application-mysql.properties ?

ok， I‘ll verify it.

**Comment by ahutsunshine** [comment]
@guoyuepeng 
If we keep and update  hibernate_mysql_pom.xml, we'd better make it similar to pom.xml. So we need to **update** 
```      
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-web</artifactId>
</dependency>
```
**to**
```
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-web</artifactId>
    <exclusions>
        <exclusion>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-logging</artifactId>
        </exclusion>
    </exclusions>
</dependency>
```
and **update** 
```
<dependency>
	<groupId>org.apache.hive</groupId>
	<artifactId>hive-metastore</artifactId>
	<version>${hive.version}</version>
</dependency>
```
**to** 
```
<dependency>
	<groupId>org.apache.hive</groupId>
	<artifactId>hive-metastore</artifactId>
	<version>${hive.version}</version>
	<exclusions>
		<exclusion>
			<groupId>org.eclipse.jetty.aggregate</groupId>
			<artifactId>jetty-all</artifactId>
		</exclusion>
		<exclusion>
			<groupId>org.eclipse.jetty.orbit</groupId>
			<artifactId>javax.servlet</artifactId>
		</exclusion>
		<exclusion>
			<groupId>javax.servlet</groupId>
			<artifactId>servlet-api</artifactId>
		</exclusion>
		<exclusion>
			<groupId>de.ruedigermoeller</groupId>
			<artifactId>fst</artifactId>
		</exclusion>
	</exclusions>
</dependency>
```.
The first update is to prevent dependency conflicts and the second update is to remove some dependencies and prevent `Caused by: java.lang.NoSuchMethodError: org.eclipse.jetty.servlet.ServletMapping.setDefault` when using Griffin for the first time.

**Comment by guoyuepeng** [comment]
> @guoyuepeng
> If we keep and update hibernate_mysql_pom.xml, we'd better make it similar to pom.xml. So we need to **update**
> 
> ```
> <dependency>
>     <groupId>org.springframework.boot</groupId>
>     <artifactId>spring-boot-starter-web</artifactId>
> </dependency>
> ```
> **to**
> 
> ```
> <dependency>
>     <groupId>org.springframework.boot</groupId>
>     <artifactId>spring-boot-starter-web</artifactId>
>     <exclusions>
>         <exclusion>
>             <groupId>org.springframework.boot</groupId>
>             <artifactId>spring-boot-starter-logging</artifactId>
>         </exclusion>
>     </exclusions>
> </dependency>
> ```
> and **update**
> 
> ```
> <dependency>
> 	<groupId>org.apache.hive</groupId>
> 	<artifactId>hive-metastore</artifactId>
> 	<version>${hive.version}</version>
> </dependency>
> ```
> **to**
> 
> ```
> <dependency>
> 	<groupId>org.apache.hive</groupId>
> 	<artifactId>hive-metastore</artifactId>
> 	<version>${hive.version}</version>
> 	<exclusions>
> 		<exclusion>
> 			<groupId>org.eclipse.jetty.aggregate</groupId>
> 			<artifactId>jetty-all</artifactId>
> 		</exclusion>
> 		<exclusion>
> 			<groupId>org.eclipse.jetty.orbit</groupId>
> 			<artifactId>javax.servlet</artifactId>
> 		</exclusion>
> 		<exclusion>
> 			<groupId>javax.servlet</groupId>
> 			<artifactId>servlet-api</artifactId>
> 		</exclusion>
> 		<exclusion>
> 			<groupId>de.ruedigermoeller</groupId>
> 			<artifactId>fst</artifactId>
> 		</exclusion>
> 	</exclusions>
> </dependency>
> ```.
> The first update is to prevent dependency conflicts and the second update is to remove some dependencies and prevent `Caused by: java.lang.NoSuchMethodError: org.eclipse.jetty.servlet.ServletMapping.setDefault` when using Griffin for the first time.
> ```

thanks, let me check whether we can leverage profile in apache community

**Comment by ahutsunshine** [comment]
BTW, currently Griffin does not support mysql 8.0 or above versions. If we support it, we still need update mysql dependency.  
e.g.
```
<dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <version>8.0.13</version>
</dependency>
```

**Comment by ahutsunshine** [comment]
@guoyuepeng
 LGTM

**Comment by guoyuepeng** [comment]
1. need to add two profile properties 
2. limit EclipseLinkJpaConfig under profile eclipselink

**Comment by guoyuepeng** [comment]
checked with apache, we better use eclipselink as jpa provider, we cannot use hibernate.

**Pull request closed without merging**
