### PR TITLE
[GRIFFIN-312] Code Style Standardization

### PR DESCRIPTION
**Pull request by chitralverma**
**What changes were proposed in this pull request?**

This PR targets the following,
- fix the various warnings during build and in source code,
- perform code formatting as per a standard style,
- fix scalastyle integration

Using the [code format from spark code style can be automatically imposed on measure module. Link: https://github.com/apache/spark/blob/master/dev/.scalafmt.conf

Since ScalaStyle targets scala source code only, it should be a part of the measure module only. Current misconfiguration is also suppressing the formatting errors 

Scalafmt is used for code formatting.

**Does this PR introduce any user-facing change?**
No

**How was this patch tested?**
Griffin test suite.

### CODE REVIEW

**Comment by chitralverma** [comment]
@wankunde @guoyuepeng Can you please review this. Thanks.

**Comment by wankunde** [comment]
@chitralverma 

The plugin name should change with the scala version,  and it has some compatibility problems with  scala 2.13.

Could you update your code?

https://issues.apache.org/jira/browse/SPARK-29293

https://github.com/apache/spark/blob/e5abbab0ed5d9d70522c1e19c53e95c631dd1565/pom.xml#L3026

scala-2.11 version:
```xml
<plugin>
                <groupId>org.antipathy</groupId>
                <artifactId>mvn-scalafmt_2.11</artifactId>
                <version>0.12_1.5.1</version>
                <configuration>
                    <parameters>${scalafmt.parameters}</parameters>
                    <skip>${scalafmt.skip}</skip>
                    <skipSources>${scalafmt.skip}</skipSources>
                    <skipTestSources>${scalafmt.skip}</skipTestSources>
                    <configLocation>${project.parent.basedir}/.scalafmt.conf</configLocation>
                </configuration>
                <executions>
                    <execution>
                        <phase>validate</phase>
                        <goals>
                            <goal>format</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```
scala-2.12 version:
```xml
    <profile>
      <id>scala-2.12</id>
      <build>
        <pluginManagement>
          <plugins>
            <!-- SPARK-29293 currently not able to update to 1.x for Scala 2.13 -->
            <plugin>
              <groupId>org.antipathy</groupId>
              <artifactId>mvn-scalafmt_2.12</artifactId>
              <version>0.12_1.5.1</version>
              <configuration>
                <parameters>${scalafmt.parameters}</parameters> <!-- (Optional) Additional command line arguments -->
                <skip>${scalafmt.skip}</skip> <!-- (Optional) skip formatting -->
                <skipSources>${scalafmt.skip}</skipSources>
                <skipTestSources>${scalafmt.skip}</skipTestSources>
                <configLocation>dev/.scalafmt.conf</configLocation> <!-- (Optional) config location -->
              </configuration>
              <executions>
                <execution>
                  <phase>validate</phase>
                  <goals>
                    <goal>format</goal>
                  </goals>
                </execution>
              </executions>
            </plugin>
          </plugins>
        </pluginManagement>
      </build>
    </profile>
```

**Comment by chitralverma** [comment]
@wankunde 
I've linked the scalafmt version to scala binary version. 

But your note refers to its use in spark. The version problem actually exists over there as spark has differerent maven build profiles. Since Griffin does not have a dedicated build profile for 2.12 or 2.13, there should be no problem here.

Can you review this/

**Comment by wankunde** [comment]
@chitralverma 

LGTM

`scalafmt` plugin is more strict with scala code than `scalastyle-maven-plugin`.
Could you also update the develop document `https://github.com/apache/griffin/blob/master/griffin-doc/dev/code-style.md` for new developers.

Thanks.

**Comment by chitralverma** [comment]
sure. will do!

**Comment by chitralverma** [comment]
@wankunde 
I've added the code style documentation for scala. Please have a look and suggest changes if any.

**Comment by wankunde** [comment]
Thanks @chitralverma 

LGTM

**Comment by toyboxman** [comment]
@chitralverma ,

Good Job!

**Comment by chitralverma** [comment]
thanks!

**Pull request closed without merging**
