### PR TITLE
[GRIFFIN-347] Setup automated workflows for greetings and stale checks

### PR DESCRIPTION
**Pull request by chitralverma**
**What changes were proposed in this pull request?**

Add a GitHub Workflow that automatically checks for stale PRs and tags/ closes them when inactive for a long duration.

> This workflow will run every day at 00.00 UTC to check for any issues/ PRs that have been inactive for over 30 and will close them in another 15 days.
> Additionally, the stale PRs will be marked with a `no-pr-activity` label. PR s having `awaiting-approval`, `work-in-progress` or `wip` label are excluded from this check.

Greet new users

> Add a GitHub Workflow that automatically greets new users on their first PR.

**Does this PR introduce any user-facing change?**
Yes. Users will see comments on PRs and Issues

**How was this patch tested?**
No test required

### CODE REVIEW

**Comment by guoyuepeng** [comment]
@chitralverma 

Good to know this feature, have you tested it on our jira?

Thanks,
William

**Comment by chitralverma** [comment]
> @chitralverma
> 
> Good to know this feature, have you tested it on our jira?
> 
> Thanks,
> William

Hi William, the bot only closes the issues and PRs on Github. Do you want me to update this to close the tickets automatically as well?

**Comment by guoyuepeng** [comment]
> > @chitralverma
> > Good to know this feature, have you tested it on our jira?
> > Thanks,
> > William
> 
> Hi William, the bot only closes the issues and PRs on Github. Do you want me to update this to close the tickets automatically as well?

Cool, please close the ticket at the same time.
BTW, when you say close the issue, do you mean close JIRA tickets? Where are those issues documented?

Thanks,
William

**Comment by chitralverma** [comment]
@guoyuepeng @wankunde can you review this?
I have updated the scope of this ticket. The automation now focuses only on PRs now since Jira handles all the issues for Apache projects.

We can ideally close the Jira tickets from this automation as well but that will involve the creation of tokens and setting them like secrets in the repo settings. Also, that automation should be set up directly in Jira as Github won't be able to track the activity on a Jira ticket from here.

**Comment by guoyuepeng** [comment]
@chitralverma 
since we have [GRIFFIN-360], do we still need this PR?

**Comment by chitralverma** [comment]
> @chitralverma
> since we have [GRIFFIN-360], do we still need this PR?

Yes @guoyuepeng. This MR is about automating closing of stale PRs on github when they lack any activity for long duration.
I see that you recently closed a lot of PRs as they were very old. 

This PR does the same thing, it tags PRs as stale and closes them if there is no activity.

**Pull request merged**
