### PR TITLE
[GRIFFIN-326] New Data Connector for Elasticsearch

### PR DESCRIPTION
**Pull request by chitralverma**
**What changes were proposed in this pull request?**

This ticket proposes the following changes,
- Deprecate the current implementation in favour of the direct implementation in the official [elasticsearch-hadoop](https://github.com/elastic/elasticsearch-hadoop/tree/master/spark/sql-20) library.
- This library is built on DataSource API built on spark 2.2.x+ and thus brings support for filter pushdowns, column pruning, unified read and write and additional optimizations.
- Many configuration options are available for ES connectivity, [check here](https://github.com/elastic/elasticsearch-hadoop/blob/master/mr/src/main/java/org/elasticsearch/hadoop/cfg/ConfigurationOptions.java).
- Any filters can be applied as expressions directly on the data frame and are pushed automatically to the source.

**Does this PR introduce any user-facing change?**
Yes. As mentioned above, the old connector has been deprecated and config structure for Elasticsearch data connector has changed now.

**How was this patch tested?**
Griffin test suite and additional unit test cases

### CODE REVIEW

**Comment by chitralverma** [comment]
@wankunde @guoyuepeng Can you please review this. Thanks.

Also, I think the build is stuck?

**Comment by guoyuepeng** [comment]
Not sure what happened on CI, let me check.

**Comment by wankunde** [comment]
@chitralverma @guoyuepeng 

`FileBasedDataConnectorTest` will generate some test data files in `file://${getClass.getResource("/").getPath}` directory, I am not sure travis has some restrictions on this directory. If this problem occurs again, @chitralverma could put those files directly into test resources directory.

@chitralverma could you update your PR with little change and try again?

**Comment by DragonPrince1992** [comment]
es的hostname都配置正确，在job执行完成之后，es里边查询数据是没有的，这个是怎么回事？

**Comment by chitralverma** [comment]
This is a source connector, not a sink. I'm working on it separately

**Comment by DragonPrince1992** [comment]
&nbsp;


I could not see&nbsp;&nbsp;healthy graphics ,how to solve it


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Chitral Verma"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月13日(星期一) 下午3:03
收件人:&nbsp;"apache/griffin"<griffin@noreply.github.com&gt;;
抄送:&nbsp;"苍龙七宿"<1982037728@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [apache/griffin] [GRIFFIN-326] New Data Connector for Elasticsearch (#569)





 
This is a source connector, not a sink. I'm working on it separately

**Comment by chitralverma** [comment]
also, you have to use `es.nodes` not `es.hostname`

This PR has not been closed yet

**Comment by DragonPrince1992** [comment]
I can't get it.&nbsp;Can I fix this as configuration?&nbsp;&nbsp;Under file&nbsp;&nbsp;\griffin-master\measure\src\main\resources\env-batch.json


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Chitral Verma"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月13日(星期一) 下午3:09
收件人:&nbsp;"apache/griffin"<griffin@noreply.github.com&gt;;
抄送:&nbsp;"苍龙七宿"<1982037728@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [apache/griffin] [GRIFFIN-326] New Data Connector for Elasticsearch (#569)





 
also, you have to use es.nodes not es.hostname
 
This PR has not been closed yet

**Comment by DragonPrince1992** [comment]
Can I add you a WeChat?It's easier to communicate.





&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Chitral Verma"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月13日(星期一) 下午3:09
收件人:&nbsp;"apache/griffin"<griffin@noreply.github.com&gt;;
抄送:&nbsp;"苍龙七宿"<1982037728@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [apache/griffin] [GRIFFIN-326] New Data Connector for Elasticsearch (#569)





 
also, you have to use es.nodes not es.hostname
 
This PR has not been closed yet

**Comment by chitralverma** [comment]
@wankunde the build has failed again, due to some error on the UI side. 
not sure of the fix here.

**Comment by wankunde** [comment]
@chitralverma 

https://github.com/DefinitelyTyped/DefinitelyTyped/issues/43977

There seems to be mismatch with npm packages. @guoyuepeng  Can you help with this  ?

**Comment by guoyuepeng** [comment]
> @chitralverma
> 
> [DefinitelyTyped/DefinitelyTyped#43977](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/43977)
> 
> There seems to be mismatch with npm packages. @guoyuepeng Can you help with this ?

we need to downgrade jquery version.

**Comment by guoyuepeng** [comment]
> > @chitralverma
> > [DefinitelyTyped/DefinitelyTyped#43977](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/43977)
> > There seems to be mismatch with npm packages. @guoyuepeng Can you help with this ?
> 
> we need to downgrade jquery version.

@chitralverma @wankunde 

we have temporarily downgrade jquery version in master.
you can retry to verify.
thanks.

**Comment by chitralverma** [comment]
Anyway to retrigger a build without a blank commit?

**Comment by guoyuepeng** [comment]
> Anyway to retrigger a build without a blank commit?

let me figure out how to trigger the build.

**Comment by guoyuepeng** [comment]
retest this, please

**Comment by guoyuepeng** [comment]
re-trigger build

**Comment by icesmartjuan** [comment]
Hi @chitralverma , the type seems added in typescript 2.7, can you please have a try? (it works fine now)
- please change typescript version from `"typescript": "~2.3.3",` to `"typescript": "~2.7",`  in `package.json` , 
- remove `node_modules ` and `package-lock.json`, 
- re-run `npm install`, 
- then `npm start`, it should run successfully

**Comment by chitralverma** [comment]
@icesmartjuan thanks, I'll try that and commit

**Comment by chitralverma** [comment]
@guoyuepeng @wankunde I've made the necessary changes in this PR to fix failures, can you please review and merge this now.

Key Changes since failures:
- As per @icesmartjuan suggestion, updated the version of `typescript`.
- As per @wankunde suggestion, refactored `FileBasedDataConnector`.
- Refactored `ElasticSearchDataConnectorTest` as it was too resource-intensive for the builder.
- Minor changes to other connectors as they were suppressing read exceptions.

**Comment by guoyuepeng** [comment]
reviewed, will merge it.

**Comment by chitralverma** [comment]
@guoyuepeng Seems like a build has been running for this for month now. Can you check this.

https://travis-ci.org/github/apache/griffin/builds/694599100?utm_source=github_status&utm_medium=notification

**Pull request closed without merging**
